sudo: false

language: perl

perl:
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"
    - "5.10"

install:
    - cpanm --no-skip-satisfied ExtUtils::MakeMaker
    - dzil authordeps --missing | cpanm  --no-skip-satisfied || { cat ~/.cpanm/build.log ; false ; }
    - dzil -Ilib listdeps --author --missing | cpanm --no-skip-satisfied || { cat ~/.cpanm/build.log ; false ; }

script:
    - dzil -Ilib test --author --release
